#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-POSIX-strftime-Compiler
Version  : 0.42
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/K/KA/KAZEBURO/POSIX-strftime-Compiler-0.42.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/K/KA/KAZEBURO/POSIX-strftime-Compiler-0.42.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libp/libposix-strftime-compiler-perl/libposix-strftime-compiler-perl_0.42-1.debian.tar.xz
Summary  : 'GNU C library compatible strftime for loggers and servers'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-POSIX-strftime-Compiler-license
Requires: perl-POSIX-strftime-Compiler-man
BuildRequires : perl(Module::Build)

%description
[![Build Status](https://travis-ci.org/kazeburo/POSIX-strftime-Compiler.svg?branch=master)](https://travis-ci.org/kazeburo/POSIX-strftime-Compiler)
# NAME

%package license
Summary: license components for the perl-POSIX-strftime-Compiler package.
Group: Default

%description license
license components for the perl-POSIX-strftime-Compiler package.


%package man
Summary: man components for the perl-POSIX-strftime-Compiler package.
Group: Default

%description man
man components for the perl-POSIX-strftime-Compiler package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n POSIX-strftime-Compiler-0.42
mkdir -p %{_topdir}/BUILD/POSIX-strftime-Compiler-0.42/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/POSIX-strftime-Compiler-0.42/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-POSIX-strftime-Compiler
cp LICENSE %{buildroot}/usr/share/doc/perl-POSIX-strftime-Compiler/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/POSIX/strftime/Compiler.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-POSIX-strftime-Compiler/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/POSIX::strftime::Compiler.3
